package com.ea.springbasic.models;

/**
 * As of JDK 14, we can replace our repetitious data classes with records.
 * Records are immutable data classes that require only the type and name of fields.
 * The equals, hashCode, and toString methods, as well as the private,
 * final fields and public constructor, are generated by the Java compiler..
 */
public record UserDetails(String username, String password) {

}
